# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 700)
        MainWindow.setStyleSheet("#title_frame {\n"
"    border-top-left-radius: 10px;  /* Rounds the top left corner of the title frame */\n"
"    background-color: #4789f3;  /* Sets a blue background color for the title frame, making it stand out */\n"
"}\n"
"\n"
"#main_frame {\n"
"    border-bottom-right-radius: 10px;  /* Rounds the bottom right corner of the main frame */\n"
"    border-bottom-left-radius: 10px;  /* Rounds the bottom left corner of the main frame */\n"
"    background-color: #d8d8d8;  /* Sets a light grey background color for the main frame */\n"
"}\n"
"\n"
"#title_frame QLabel {\n"
"    color: #fff;  /* Sets the text color to white for labels in the title frame for better readability */\n"
"    background-color: transparent;  /* Ensures the label background is transparent */\n"
"}\n"
"\n"
"#icon_label {\n"
"    min-width: 30px;  /* Sets a minimum width for the icon label */\n"
"    min-height: 30px;  /* Sets a minimum height for the icon label */\n"
"    max-width: 30px;  /* Sets a maximum width for the icon label to ensure it stays a fixed size */\n"
"    max-height: 30px;  /* Sets a maximum height for the icon label */\n"
"    border-radius: 15px;  /* Rounds the edges of the icon label to make it circular */\n"
"    border: 1px solid #fff;\n"
"}\n"
"\n"
"#title_frame QPushButton {\n"
"    border: none;  /* Removes the border from QPushButton in the title frame for a cleaner look */\n"
"    width: 50px;  /* Sets the width of the button */\n"
"    height: 40px;  /* Sets the height of the button */\n"
"}\n"
"\n"
"#maxmize_btn:hover, #minimize_btn:hover {\n"
"    background-color: #d8d8d8;  /* Changes the background color of maximize and minimize buttons on hover for visual feedback */\n"
"}\n"
"\n"
"#close_btn:hover {\n"
"    background-color: #c42b1c;  /* Changes the background color of the close button on hover to a distinct red, indicating a destructive action */\n"
"}\n"
"\n"
"#close_btn, #title_frame {\n"
"    border-top-right-radius: 10px;  /* Rounds the top right corner of the close button and the title frame for a softened edge */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.title_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_3.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_label = QtWidgets.QLabel(parent=self.title_frame)
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout_2.addWidget(self.icon_label)
        self.label_2 = QtWidgets.QLabel(parent=self.title_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(952, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimize_btn = QtWidgets.QPushButton(parent=self.title_frame)
        self.minimize_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icon/minimize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimize_btn.setIcon(icon)
        self.minimize_btn.setIconSize(QtCore.QSize(20, 20))
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout.addWidget(self.minimize_btn)
        self.maxmize_btn = QtWidgets.QPushButton(parent=self.title_frame)
        self.maxmize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\icon/full_window.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(".\\icon/normal_window.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.maxmize_btn.setIcon(icon1)
        self.maxmize_btn.setObjectName("maxmize_btn")
        self.horizontalLayout.addWidget(self.maxmize_btn)
        self.close_btn = QtWidgets.QPushButton(parent=self.title_frame)
        self.close_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\icon/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon2)
        self.close_btn.setIconSize(QtCore.QSize(20, 20))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.title_frame, 0, 0, 1, 1)
        self.main_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout.addWidget(self.main_frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Window Title"))
