# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/pingl/Desktop/ChatGTP\widgets\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1343, 810)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/open AI.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"}\n"
"\n"
"\n"
"#menu_frame QPushButton {\n"
"    text-align: left;\n"
"    color: #fff;\n"
"    border: none;\n"
"    padding:10px 10px;\n"
"    border-radius: 5px;\n"
"    background: none;\n"
"}\n"
"\n"
"#menu_frame QFrame {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#new_chat_btn {\n"
"    border: 1px solid #4d4d4f;\n"
"    border-radius: 5px;\n"
"    text-align: left;\n"
"    color: #fff;\n"
"    padding:10px;\n"
"}\n"
"\n"
"\n"
"#side_widget,\n"
"#side_widget QPushButton,\n"
"#chat_list {\n"
"    background-color: #202123;\n"
"}\n"
"\n"
"#side_widget QPushButton:hover,\n"
"#chat_list::item:hover,\n"
"#user_frame:hover,\n"
"#menu_frame QFrame:hover\n"
" {\n"
"    background-color: #2a2b32;\n"
"}\n"
"\n"
"#user_frame:hover \n"
" {\n"
"    QPushButton {background-color: #2a2b32;}\n"
"}\n"
"\n"
"\n"
"#chat_list::item:selected {\n"
"    background-color: #343541;\n"
"}\n"
"\n"
"\n"
"#chat_list {\n"
"    border: none;\n"
"}\n"
"\n"
"#chat_list::item {\n"
"    color: #fff;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    margin-top:5px;\n"
"}\n"
"\n"
"#chat_list_scrollArea {\n"
"  border: none;\n"
"}\n"
"\n"
"#menu_frame {\n"
"    border-top: 0.5px solid #4d4d4f;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"     border: none;\n"
"     background: #202123;\n"
"     width: 8px;\n"
"     margin: 0;\n"
"    border-radius: 4px;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: #565869;\n"
"     min-height: 20px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
" QScrollBar::add-line:vertical {\n"
"     border:none;\n"
"     background: #202123;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"QScrollBar::handle:hover {    \n"
"    background-color: #acacbe;\n"
"}\n"
"\n"
"\n"
"\n"
"/* #565869 */\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.side_widget = QtWidgets.QWidget(self.centralwidget)
        self.side_widget.setMinimumSize(QtCore.QSize(241, 0))
        self.side_widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_widget.setObjectName("side_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.side_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.new_chat_btn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.new_chat_btn.setFont(font)
        self.new_chat_btn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/add_google_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_chat_btn.setIcon(icon1)
        self.new_chat_btn.setIconSize(QtCore.QSize(18, 18))
        self.new_chat_btn.setObjectName("new_chat_btn")
        self.verticalLayout_2.addWidget(self.new_chat_btn)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.side_widget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chat_list = QtWidgets.QListView(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chat_list.setFont(font)
        self.chat_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chat_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_list.setObjectName("chat_list")
        self.gridLayout.addWidget(self.chat_list, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.menu_frame = QtWidgets.QFrame(self.side_widget)
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout.setContentsMargins(9, 5, 9, 5)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.menu_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMaximumSize(QtCore.QSize(16, 16))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background: none;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_8.addWidget(self.pushButton_9)
        self.verticalLayout.addWidget(self.frame_7)
        self.user_frame = QtWidgets.QFrame(self.menu_frame)
        self.user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_frame.setObjectName("user_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.user_frame)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.user_frame)
        self.label_2.setMaximumSize(QtCore.QSize(17, 17))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/user.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton_10 = QtWidgets.QPushButton(self.user_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background: none;")
        self.pushButton_10.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.new_label = QtWidgets.QLabel(self.user_frame)
        self.new_label.setMaximumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_label.setFont(font)
        self.new_label.setStyleSheet("#new_label {\n"
"    padding: 5px;\n"
"    border-radius: 6px;\n"
"    background: #fae69e;\n"
"}")
        self.new_label.setAlignment(QtCore.Qt.AlignCenter)
        self.new_label.setObjectName("new_label")
        self.horizontalLayout_2.addWidget(self.new_label)
        self.verticalLayout.addWidget(self.user_frame)
        self.frame_10 = QtWidgets.QFrame(self.menu_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_16 = QtWidgets.QLabel(self.frame_10)
        self.label_16.setMinimumSize(QtCore.QSize(16, 16))
        self.label_16.setMaximumSize(QtCore.QSize(16, 16))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/icons/icons/robot.svg"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.comboBox = QtWidgets.QComboBox(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox.setStyleSheet("QComboBox {\n"
"border: none;\n"
"background: transparent;\n"
"color: #fff;\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:editable {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    padding-top:5px;\n"
"    font-size: 11px;\n"
"    background-color: #2a2b32;\n"
"    outline: 0px;  /*去虚线*/\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:5px;\n"
"    background: transparent;\n"
"    padding:5px;\n"
"    color: #fff;\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_6 = QtWidgets.QFrame(self.menu_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMaximumSize(QtCore.QSize(16, 16))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/icons/dark.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background: none;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.menu_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMaximumSize(QtCore.QSize(16, 16))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/update.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background: none;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.menu_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(17, 17))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/logout.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background: none;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.menu_frame)
        self.horizontalLayout_3.addWidget(self.side_widget)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setStyleSheet("background: #fff;")
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 20)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.input_frame = QtWidgets.QFrame(self.main_widget)
        self.input_frame.setMinimumSize(QtCore.QSize(650, 0))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.input_frame.setStyleSheet("#input_frame\n"
"{\n"
"    border: 1px solid #e5e5e5;\n"
"    background: #fff;\n"
"    border-radius: 5px;\n"
"}")
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout_2.setContentsMargins(10, 10, 5, 10)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.send_btn = QtWidgets.QPushButton(self.input_frame)
        self.send_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.send_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.send_btn.setStyleSheet("#send_btn {\n"
"border: none;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"#send_btn:hover {\n"
"    background: #ececf1;\n"
"}")
        self.send_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/send.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_btn.setIcon(icon2)
        self.send_btn.setIconSize(QtCore.QSize(16, 16))
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.input_textEdit = QtWidgets.QTextEdit(self.input_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_textEdit.setFont(font)
        self.input_textEdit.setStyleSheet("border: none;")
        self.input_textEdit.setObjectName("input_textEdit")
        self.gridLayout_2.addWidget(self.input_textEdit, 0, 0, 2, 1)
        self.gridLayout_3.addWidget(self.input_frame, 1, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1093, 562))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setVerticalSpacing(50)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 3)
        self.horizontalLayout_3.addWidget(self.main_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1343, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChatGPT"))
        self.new_chat_btn.setText(_translate("MainWindow", "New Chat"))
        self.pushButton_9.setText(_translate("MainWindow", "Clear conversations"))
        self.pushButton_10.setText(_translate("MainWindow", "Upgrade to Plus"))
        self.new_label.setText(_translate("MainWindow", "NEW"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ChatGPT"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Google Chat"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Baidu Chat"))
        self.comboBox.setItemText(3, _translate("MainWindow", "......."))
        self.pushButton_8.setText(_translate("MainWindow", "Dark mode"))
        self.pushButton_5.setText(_translate("MainWindow", "Updates && FAQ"))
        self.pushButton_6.setText(_translate("MainWindow", "Log out"))
from static import resource_rc
